server:
  port: 8080

spring:
  application:
    name: ecommerce-backend

  data:
    mongodb:
      uri: mongodb+srv://gaikwadsoham5117_db_user:9gexBk1UURsrvZrs@salesdashboard.hfwibkb.mongodb.net/SalesDashboard?appName=SalesDashboard
app:
  seed-data: true